name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t herdau/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true herdau/docker-react npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Docker-react-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-024925203769
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
