name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t herdau/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true herdau/docker-react npm run test